### ISSUE TITLE
Oups

### ISSUE THREAD

**Issue by DrouSoft** [Dweaver309/NETMF4_4FirmwareUpdate#1]
Hi,

Doesn't work under VS2017...

**Comment by Dweaver309** [comment]
To use  4.4 you will need a to update VS2017 with a new VSIX. I just saw this posted on the GHI Electronic's web site. https://marketplace.visualstudio.com/items?itemName=PervasiveDigitalLLC.pdnetmf-extension

**Comment by DrouSoft** [comment]
Thanks
